apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  template:
    metadata:
      name: nginx-pod
      labels:
        demo: k8s-handson
        role: presetdemo
    spec:
      containers:
      - name: nginx-server
        image: ramaraja/webserver:1.0
        imagePullPolicy: IfNotPresent

  replicas: 2
  selector:
    matchLabels:
      demo: k8s-handson

  strategy:
    type: RollingUpdate
