apiVersion: v1
kind: PersistentVolume
metadata:
  name: pvtest
  labels:
    app: webserver
spec:
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: "example-nfs"
  capacity:
    storage: 1Gi
